stages:
  train:
    cmd: '& " C:/Users/THABO MATHEBULA/AppData/Local/Programs/Python/Python311/python.exe\
      scripts/train.py'
    deps:
    - data/call_center.csv
    - data/claims.csv
    - scripts/train.py
    outs:
    - model.pkl
    - results.csv
    metrics:
    - metrics.json:
        cache: false
