# src/scripts/apply_branding.py
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from fpdf import FPDF
from datetime import datetime
import src.utils.loaders as loaders
from src.utils.branding import get_theme_assets
from src.utils.plot_utils import save_professional_plot   

# Directories
ASSETS_DIR = Path("src/assets")
EXPORT_DIR = Path("src/exports")
EXPORT_DIR.mkdir(parents=True, exist_ok=True)   # ✅ auto-create if missing

# --- Professional Plot Helper ---
def save_professional_plot(fig, filename: Path, dpi: int = 120):
    """Save a matplotlib figure with StreamIQ's professional sizing standards."""
    sns.set(font_scale=0.9)
    fig.set_size_inches(5, 4)
    fig.tight_layout()
    fig.savefig(filename, dpi=dpi)
    print(f"📊 Professional plot saved to {filename}")

# --- Theme-aware Chart Watermark ---
def apply_streamiq_watermark(fig, theme="light", alpha=0.15, position=(0.8, 0.05)):
    """Overlay StreamIQ watermark on a Matplotlib figure."""
    assets = get_theme_assets()
    watermark_path = assets["watermark"] if assets else ASSETS_DIR / "streamiq_logo_gray.png"
    try:
        watermark = mpimg.imread(watermark_path)
        ax = fig.add_axes([position[0], position[1], 0.15, 0.15], anchor='SE', zorder=10)
        ax.imshow(watermark, alpha=alpha)
        ax.axis("off")
    except Exception:
        pass  # fail gracefully if logo missing

# --- Chart Export ---
def watermark_chart(fig=None, theme="light", filename="chart_streamiq.png"):
    if fig is None:
        fig, ax = plt.subplots()
        ax.plot([1, 2, 3, 4], [10, 20, 25, 30])
    apply_streamiq_watermark(fig, theme=theme)
    save_professional_plot(fig, EXPORT_DIR / filename)
    return EXPORT_DIR / filename

# --- CSV Export ---
def watermark_csv(data=None, theme="light", filename="streamiq_export.csv", summary=None):
    if loaders.USE_DUMMY or data is None:
        data = {"Conversation": [1, 2, 3], "Insight": ["Demo A", "Demo B", "Demo C"]}
    df = pd.DataFrame(data)
    footer = f"Generated by StreamIQ [{theme.capitalize()} Mode]"
    df.loc[len(df)] = ["", footer]
    if summary:
        for k, v in summary.items():
            df.loc[len(df)] = [k, v]
    df.to_csv(EXPORT_DIR / filename, index=False)
    return EXPORT_DIR / filename

# --- Excel Export ---
def watermark_excel(data=None, theme="light", filename="streamiq_export.xlsx", summary=None):
    if loaders.USE_DUMMY or data is None:
        data = {"Conversation": [1, 2, 3], "Insight": ["Demo A", "Demo B", "Demo C"]}
    df = pd.DataFrame(data)
    footer = f"Generated by StreamIQ [{theme.capitalize()} Mode]"
    df.loc[len(df)] = ["", footer]
    if summary:
        for k, v in summary.items():
            df.loc[len(df)] = [k, v]
    df.to_excel(EXPORT_DIR / filename, index=False, engine="openpyxl")
    return EXPORT_DIR / filename

# --- PDF Export ---
def watermark_pdf(text="StreamIQ Insights Report", theme="light", filename="streamiq_report.pdf", summary=None):
    assets = get_theme_assets()
    watermark_path = assets["watermark"] if assets else ASSETS_DIR / "streamiq_logo_gray.png"
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", size=12)
    pdf.multi_cell(0, 10, text)
    if summary:
        for k, v in summary.items():
            pdf.cell(0, 10, f"{k}: {v}", ln=True)
    try:
        pdf.image(str(watermark_path), x=150, y=250, w=40, h=20)
    except Exception:
        pass
    pdf.output(str(EXPORT_DIR / filename))
    return EXPORT_DIR / filename

# --- Unified Export Manager ---
def export_with_branding(data=None, fig=None, export_type="csv", theme="light", summary=None):
    if export_type == "csv":
        return watermark_csv(data, theme=theme, summary=summary)
    elif export_type == "xlsx":
        return watermark_excel(data, theme=theme, summary=summary)
    elif export_type == "png":
        return watermark_chart(fig, theme=theme)
    elif export_type == "pdf":
        return watermark_pdf(theme=theme, summary=summary)
    else:
        raise ValueError("Unsupported export_type. Use 'csv', 'xlsx', 'png', or 'pdf'.")

# --- CLI Entry Point ---
if __name__ == "__main__":
    print("Applying StreamIQ branding...")
    summary = {
        "Total Records": 3,
        "Last Refresh": datetime.now().isoformat(timespec="seconds"),
        "Mode": "Dummy" if loaders.USE_DUMMY else "Backend"
    }
    print("CSV saved to:", watermark_csv(theme="light", summary=summary))
    print("Excel saved to:", watermark_excel(theme="light", summary=summary))
    print("Chart saved to:", watermark_chart(theme="light"))
    print("PDF saved to:", watermark_pdf(theme="light", summary=summary))
    print("📊 Branded exports saved to src/exports/")
