import os
import pandas as pd
import altair as alt
import streamlit as st
import pytest
from src.utils import branding

# -------------------------------
# Fixture: create dummy asset files
# -------------------------------
@pytest.fixture(autouse=True)
def ensure_assets(tmp_path, monkeypatch):
    assets_dir = tmp_path / "assets"
    assets_dir.mkdir()

    # Create dummy files for all expected assets
    dummy_files = {
        "streamiq_logo.png",
        "streamiq_logo_dark.png",
        "streamiq_logo_gray.png",
        "streamiq_favicon_dark.png",
        "streamiq_banner.png"
    }
    for fname in dummy_files:
        (assets_dir / fname).write_text("dummy")

    # Monkeypatch get_theme_assets to point to tmp_path assets
    def fake_get_theme_assets():
        theme_base = st.get_option("theme.base")
        if theme_base == "dark":
            return {
                "logo": str(assets_dir / "streamiq_logo_dark.png"),
                "favicon": str(assets_dir / "streamiq_favicon_dark.png"),
                "banner": str(assets_dir / "streamiq_banner.png"),
                "watermark": str(assets_dir / "streamiq_logo_gray.png")
            }
        else:
            return {
                "logo": str(assets_dir / "streamiq_logo.png"),
                "favicon": str(assets_dir / "streamiq_favicon_dark.png"),
                "banner": str(assets_dir / "streamiq_banner.png"),
                "watermark": str(assets_dir / "streamiq_logo.png")
            }

    monkeypatch.setattr(branding, "get_theme_assets", fake_get_theme_assets)
    return assets_dir

# -------------------------------
# Tests
# -------------------------------
def test_get_theme_assets_light(monkeypatch):
    monkeypatch.setattr(st, "get_option", lambda key: "light")
    assets = branding.get_theme_assets()
    for key in ["logo", "favicon", "banner", "watermark"]:
        assert key in assets
        assert os.path.exists(assets[key])

def test_get_theme_assets_dark(monkeypatch):
    monkeypatch.setattr(st, "get_option", lambda key: "dark")
    assets = branding.get_theme_assets()
    for key in ["logo", "favicon", "banner", "watermark"]:
        assert key in assets
        assert os.path.exists(assets[key])

def test_export_pdf_with_logo(tmp_path):
    filename = tmp_path / "report.pdf"
    branding.export_pdf_with_logo(str(filename))
    assert os.path.exists(filename)
    assert filename.stat().st_size > 0

def test_export_excel_with_branding(tmp_path):
    df = pd.DataFrame({"category": ["A", "B"], "value": [1, 2]})
    filename = tmp_path / "data.xlsx"
    branding.export_excel_with_branding(df, str(filename))
    assert os.path.exists(filename)
    assert filename.stat().st_size > 0

def test_export_csv_with_branding(tmp_path):
    df = pd.DataFrame({"category": ["A", "B"], "value": [1, 2]})
    filename = tmp_path / "data.csv"
    branding.export_csv_with_branding(df, str(filename))
    with open(filename, "r", encoding="utf-8") as f:
        content = f.read()
    assert "Generated by StreamIQ" in content

def test_add_chart_watermark():
    df = pd.DataFrame({"category": ["A"], "value": [1]})
    chart = alt.Chart(df).mark_bar().encode(x="category", y="value")
    branded_chart = branding.add_chart_watermark(chart)
    assert isinstance(branded_chart, alt.LayerChart)
    assert len(branded_chart.layer) == 2
